[versions]
kotlin = "1.9.23"
agp = "8.2.2"
compose = "1.6.11"
androidx-activityCompose = "1.9.0"
androidx-datastore = "1.1.1"
androidx-coreSplashscreen = "1.0.1"
healthConnect = "1.1.0-alpha07"
lifecycleViewmodelCompose = "2.8.0"
kotlinxCoroutines = "1.8.1"
multiplatformSettings = "1.1.1"
kotlinxDatetime = "0.6.0"
androidMinSdk = "26"
androidCompileSdk = "34"
androidTargetSdk = "34"

[libraries]
# Multiplataforma
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }

# Solo Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-coreSplashscreen" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
androidx-health-connect = { module = "androidx.health.connect:connect-client", version.ref = "healthConnect" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
